baseurl: /albuquerque
permalink: pretty
future: true
markdown: kramdown
paginate: 5
repo: albuquerque
github_org: maptime
maptime:
  chapter: MaptimeABQ
  twitter: MaptimeABQ
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
